"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-15 17:42:14.757212
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WRITER', 'PLAYER', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('map_image', sa.String(length=512), nullable=True),
    sa.Column('correct_location_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer_text', sa.String(length=255), nullable=True),
    sa.Column('truth_story', sa.Text(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('timers', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correct_location_id'], ['locations.id'], name='fk_scenario_correct_location', use_alter=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_genre_id'), 'scenarios', ['genre_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('trigger_type', sa.Enum('EVIDENCE_REVEALED', 'EVIDENCE_COMBINED', 'LOCATION_VISITED', 'PHASE_STARTED', 'VOTE_RESULT', name='triggertype', native_enum=False), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=False),
    sa.Column('effect_type', sa.Enum('UNLOCK_EVIDENCE', 'LOCK_EVIDENCE', 'ADD_TIME', 'REMOVE_TIME', 'REVEAL_HINT', 'NEW_SITUATION_TEXT', 'SWAP_ROLE_INFO', name='effecttype', native_enum=False), nullable=False),
    sa.Column('effect_payload', sa.JSON(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=False),
    sa.Column('fire_once', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_scenario_id'), 'events', ['scenario_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=False),
    sa.Column('map_y', sa.Float(), nullable=False),
    sa.Column('is_correct_answer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_scenario_id'), 'locations', ['scenario_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('can_be_insider', sa.Boolean(), nullable=False),
    sa.Column('special_ability', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_scenario_id'), 'roles', ['scenario_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('DOCUMENT', 'WITNESS', 'PHYSICAL', 'MEDICAL', 'RUMOR', name='evidencetype', native_enum=False), nullable=False),
    sa.Column('is_red_herring', sa.Boolean(), nullable=False),
    sa.Column('reveal_phase', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('starts_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_role_id'), 'evidence', ['role_id'], unique=False)
    op.create_index(op.f('ix_evidence_scenario_id'), 'evidence', ['scenario_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOBBY', 'IN_PROGRESS', 'FINISHED', 'ABORTED', name='gamestatus', native_enum=False), nullable=False),
    sa.Column('current_phase', sa.Enum('LOBBY', 'INTRO', 'EVIDENCE', 'DISCUSSION', 'EVENT', 'VOTE', 'INSIDER_GUESS', 'RESULT', name='gamephase', native_enum=False), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('phase_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chosen_location_id', sa.Integer(), nullable=True),
    sa.Column('chosen_answer_text', sa.String(length=255), nullable=True),
    sa.Column('insider_player_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('INVESTIGATORS_WIN', 'INSIDER_WIN', 'UNRESOLVED', name='gameoutcome', native_enum=False), nullable=True),
    sa.Column('insider_caught', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chosen_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_code'), 'games', ['code'], unique=True)
    op.create_index(op.f('ix_games_scenario_id'), 'games', ['scenario_id'], unique=False)
    op.create_table('game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('actor_player_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_logs_game_id'), 'game_logs', ['game_id'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_insider', sa.Boolean(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('revealed_evidence', sa.JSON(), nullable=False),
    sa.Column('voted_location_id', sa.Integer(), nullable=True),
    sa.Column('guessed_insider_player_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_game_user')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_players_user_id'), 'game_players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_players_user_id'), table_name='game_players')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_game_logs_game_id'), table_name='game_logs')
    op.drop_table('game_logs')
    op.drop_index(op.f('ix_games_scenario_id'), table_name='games')
    op.drop_index(op.f('ix_games_code'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_evidence_scenario_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_role_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_roles_scenario_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locations_scenario_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_events_scenario_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_scenarios_genre_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('genres')
    # ### end Alembic commands ###
